import React from 'react';
import { DueDiligenceReport as DueDiligenceReportType } from '../types';
import { 
  ReportLogo,
  ExecutiveSummarySection,
  CompanyOverviewSection, 
  FinancialAnalysisSection,
  MarketAnalysisSection,
  RiskAssessmentSection,
  ValuationAnalysisSection,
  InvestmentRecommendationsSection
} from './';

interface DueDiligenceReportProps {
  /**
   * The due diligence report data
   */
  report: DueDiligenceReportType;
  /**
   * Whether to show the logo at the top of the report
   */
  showLogo?: boolean;
}

/**
 * Due Diligence Report component that displays the full report
 */
const DueDiligenceReport: React.FC<DueDiligenceReportProps> = ({
  report,
  showLogo = true
}) => {
  if (!report) return null;

  return (
    <div className="due-diligence-report bg-white p-8 rounded-lg shadow-md max-w-4xl mx-auto">
      {showLogo && <ReportLogo className="mb-6" />}
      
      <h1 className="text-3xl font-semibold text-gray-900 mb-2">
        {report.companyName} Due Diligence Report
      </h1>
      
      {report.reportDate && (
        <p className="text-sm text-gray-600 mb-6">
          Report Date: {new Date(report.reportDate).toLocaleDateString()}
        </p>
      )}

      {/* Executive Summary */}
      <ExecutiveSummarySection data={report.executiveSummary} />
      
      {/* Company Overview */}
      <CompanyOverviewSection data={report.companyOverview} />
      
      {/* Financial Analysis */}
      <FinancialAnalysisSection data={report.financialAnalysis} />
      
      {/* Market Analysis */}
      <MarketAnalysisSection data={report.marketAnalysis} />
      
      {/* Risk Assessment */}
      <RiskAssessmentSection data={report.riskAssessment} />
      
      {/* Valuation Analysis */}
      <ValuationAnalysisSection data={report.valuationAnalysis} />
      
      {/* Investment Recommendations */}
      <InvestmentRecommendationsSection data={report.investmentRecommendations} />

      {/* Footer */}
      <div className="mt-10 pt-6 border-t border-gray-200 text-sm text-gray-600">
        <p>This report was generated by AI Diligence Pro for informational purposes only. It does not constitute financial advice or a recommendation to buy or sell any securities.</p>
        <p className="mt-2">© {new Date().getFullYear()} AI Diligence Pro. All rights reserved.</p>
      </div>
    </div>
  );
};

export default DueDiligenceReport; 