import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ReportSection from './ReportSection';
/**
 * Investment Recommendations section of the due diligence report
 */
export const InvestmentRecommendationsSection = ({ data }) => {
    if (!data)
        return null;
    return (_jsx(ReportSection, { title: "Investment Recommendations", children: _jsxs("div", { className: "space-y-6", children: [data.summary && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Summary" }), _jsx("p", { className: "mt-2", children: data.summary })] })), data.recommendation && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Recommendation" }), _jsx("p", { className: "mt-2 font-medium text-lg", children: data.recommendation })] })), data.targetPrice && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Target Price" }), _jsxs("p", { className: "mt-2 text-lg", children: [_jsx("span", { className: "font-medium", children: data.targetPrice }), data.upside && _jsxs("span", { className: "ml-2 text-emerald-600", children: ["(+", data.upside, "% upside)"] }), data.downside && _jsxs("span", { className: "ml-2 text-red-600", children: ["(", data.downside, "% downside)"] })] })] })), data.timeline && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Investment Timeline" }), _jsx("p", { className: "mt-2", children: data.timeline })] })), data.riskLevel && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Risk Level" }), _jsx("div", { className: "mt-2", children: _jsx("span", { className: `px-3 py-1 rounded-full text-sm font-semibold ${data.riskLevel.toLowerCase() === 'high' ? 'bg-red-100 text-red-800' :
                                    data.riskLevel.toLowerCase() === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                                        'bg-green-100 text-green-800'}`, children: data.riskLevel }) })] })), data.keyFactors && data.keyFactors.length > 0 && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Key Factors for Consideration" }), _jsx("ul", { className: "mt-2 list-disc pl-5", children: data.keyFactors.map((factor, index) => (_jsx("li", { children: factor }, index))) })] })), data.catalysts && data.catalysts.length > 0 && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold", children: "Potential Catalysts" }), _jsx("ul", { className: "mt-2 list-disc pl-5", children: data.catalysts.map((catalyst, index) => (_jsx("li", { children: catalyst }, index))) })] }))] }) }));
};
export default InvestmentRecommendationsSection;
